dist: trusty
sudo: required

language: node_js

node_js:
  - "12"

services:
  - docker

before_install:
  - export DEBIAN_FRONTEND=noninteractive;
  - sudo apt-get -qq --yes update
  - yarn

test:
  - echo "no tests"

script:
  - yarn run build
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t personal-site .;
      docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD";
      docker tag personal-site gerardabello/personal-site;
      docker push gerardabello/personal-site;
    fi
